# Prometheus Template
AWSTemplateFormatVersion: 2010-09-09
Description: Prometheus Template
Resources:
  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '9090'
          ToPort: '9090'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '9100'
          ToPort: '9100'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '9093'
          ToPort: '9093'
          CidrIp: 0.0.0.0/0
      
      Tags:
        - Key: Name
          Value: Prometheus2 test

  ServerInstance: 
    Type: AWS::EC2::Instance
    Properties:
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      InstanceType: t2.micro
      ImageId: ami-09e67e426f25ce0d7
      KeyName: udacity
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          wget https://github.com/prometheus/prometheus/releases/download/v2.19.0/prometheus-2.19.0.linux-amd64.tar.gz
          sudo mv prometheus-2.19.0.linux-amd64.tar.gz /home/ubuntu
          cd /home/ubuntu
          tar xvfz prometheus-2.19.0.linux-amd64.tar.gz
        # cd /home/ubuntu/prometheus-2.19.0.linux-amd64